[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.17.1'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
hippo_aggregator = "_"
